server {
    listen       ${PORT};
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Стискання
    gzip on;
    gzip_types text/css application/javascript image/svg+xml text/plain;
    gzip_min_length 1024;

    # Кешування статичних ассетів (favicon, лого)
    location ~* \.(?:webp|jpg|jpeg|png|svg|ico|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        try_files $uri =404;
    }

    # JS/CSS — короткий кеш (часто змінюються)
    location ~* \.(?:js|css)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
        try_files $uri =404;
    }

    # SPA fallback (на випадок майбутнього роутінгу) + index
    location / {
        try_files $uri $uri/ /index.html;
    }
}
